### ISSUE TITLE
ptuning微调报错

### ISSUE THREAD

**Issue by Mou-Mou-L** [THUDM/ChatGLM2-6B#76] opened 2023-06-27 10:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ChatGLMModel' object has no attribute 'prefix_encoder

### Steps To Reproduce

[INFO|configuration_utils.py:575] 2023-06-27 18:00:29,711 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "eos_token_id": 2,
  "pad_token_id": 2,
  "transformers_version": "4.27.1"
}

Loading checkpoint shards: 100%|▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒| 7/7 [00:10<00:00,  1.48s/it]
[INFO|modeling_utils.py:3032] 2023-06-27 18:00:40,197 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[INFO|modeling_utils.py:3040] 2023-06-27 18:00:40,197 >> All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at THUDM/chatglm2-6b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
[INFO|modeling_utils.py:2690] 2023-06-27 18:00:40,478 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
Traceback (most recent call last):
  File "main.py", line 430, in <module>
    main()
  File "main.py", line 132, in main
    model.transformer.prefix_encoder.float()
  File "E:\ProgramData\anaconda3\envs\glm2\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### Environment

```markdown
- windows10
- Python:3.8
- Transformers:4.27.1cu
- PyTorch:1.18cu
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment] 2023-06-27 13:01
Duplicate of #2

**Closed by duzx16** 2023-06-27 13:01 UTC
