### ISSUE TITLE
微调脚本Windows环境下报错

### ISSUE THREAD

**Issue by isacck** [THUDM/ChatGLM2-6B#189] opened 2023-07-05 02:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Windows环境下Chatglm2-6b进行微调，报错如下，在chatglm-6b的版本，用官方微调脚本是没问题的。

RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15380) of binary: D:\Python\miniconda3\envs\ctg2\python.exe
Traceback (most recent call last):
  File "D:\Python\miniconda3\envs\ctg2\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\miniconda3\envs\ctg2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python\miniconda3\envs\ctg2\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "D:\Python\miniconda3\envs\ctg2\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "D:\Python\miniconda3\envs\ctg2\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "D:\Python\miniconda3\envs\ctg2\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "D:\Python\miniconda3\envs\ctg2\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\Python\miniconda3\envs\ctg2\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### Steps To Reproduce

windows环境下设置了 PL_TORCH_DISTRIBUTED_BACKEND=gloo
依然报错。

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by cyxdsp** [comment] 2023-07-05 03:20
我也遇到了，但他的报错结果让我感觉，他就是不支持win和macos

**Comment by hlwgy** [comment] 2023-07-05 06:59
还在研究中。
也是会遇到关于非linux下的问题。比如：
NOTE: Redirects are currently not supported in Windows or MacOs.
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.

官方推荐windows下用wsl部署和测试 https://github.com/ZhangErling/ChatGLM-6B/blob/main/deployment_windows.md 。
glm2刚推出，conda系可能会有问题。今天研究研究，不行就换成wsl。linux系统肯定是经过官方试验过的。

**Comment by duzx16** [comment] 2023-07-05 13:18
Duplicate of #195

**Closed by duzx16** 2023-07-05 13:18 UTC
